resource_group_name = "__resource_group_name__"
apim_name = "__apim_name__"
env = "__env__"
region = "__region__"
backend_storage_account_name = "__backend_storage_account_name__"
backend_container_name = "__backend_container_name__"
dev_portal_storage_account_name = "__dev_portal_storage_account_name"